apiVersion: v2
name: geth
version: 2.3.10
appVersion: v1.14.7
kubeVersion: "^1.20.0-0"
description: Official Golang implementation of the Ethereum v1 protocol.
type: application
keywords:
  - ethereum
  - blockchain
  - geth
  - p2p
home: https://www.ethereum.org/
sources:
  - https://github.com/ethereum/go-ethereum/
icon: https://raw.githubusercontent.com/ethereum/ethereum-org/master/public/images/logos/ETHEREUM-ICON_Black.png

dependencies:
  - name: common
    version: 1.x.x
    repository: https://charts.staking.galaxy.com/
